### ISSUE TITLE
npm and github versions differ a lot!

### ISSUE THREAD

**Issue by venil7** [indexiatech/re-notif#17]
whats in npm and what is here differ
documentation does not match, etc....

**Comment by jpollard-cs** [comment]
okay I've reached out to @asaf on Google+ and Twitter (sorry @asaf if you get the same message three times - wasn't sure which Google+ profile and Twitter profiles were correct)

**Comment by kylecesmat** [comment]
@jpollard-cs @asaf @venil7 Yeah, we need to publish the latest to npm. If @asaf can make me a collaborator we could self-maintain this repo. Otherwise, we could rename this package on npm? (not ideal)

**Comment by jpollard-cs** [comment]
yeah let's give it a day or two then talk about alternatives - last time I used Twitter to get in touch with him it seemed to work

**Comment by ErezSha** [comment]
@kylecesmat You are already a collaborator on this repo. @asaf made you one after #9.

**Comment by jpollard-cs** [comment]
@ErezSha I think he means on npm

**Comment by NameFILIP** [comment]
yes, and the version in npm is 1.0.2, but in the source code - 1.0.1, which is weird

**Comment by kylecesmat** [comment]
Yeah - I'm going to make a tag on this repo today and if we don't hear from @asaf soon we'll make a new package on npm

**Comment by NameFILIP** [comment]
`redux-notifications` can be a good name for a new npm package

**Comment by jpollard-cs** [comment]
or just [re-notify](https://www.npmjs.com/package/re-notify)

**Comment by kylecesmat** [comment]
I personally prefer `redux-notifications` as it seems verbose. I'm weary to change the package name and break the version history. Any reason why we shouldn't?

**Comment by jcheroske** [comment]
Has a current version been published to npm? Has the name been changed?

**Comment by jpollard-cs** [comment]
@kylecesmat I have no strong feelings either way, but at this point I think we should publish a new npm package - no disrespect meant to @asaf, of course, but I think that would be a good solution until we hear from him

**Comment by venil7** [comment]
yes please publish under new name

**Comment by kylecesmat** [comment]
Hey all! This issue can be closed, a new package has been created at `redux-notifications` here - https://www.npmjs.com/package/redux-notifications

I'd love to help continue to support this project, if @asaf no longer has time to maintain then transferring ownership could be a great option?

cc: @jpollard-cs  @venil7  @jcheroske  @NameFILIP @ErezSha
