### ISSUE TITLE
componentClassName has no affect when passed as action payload

### ISSUE THREAD

**Issue by SabeehY** [indexiatech/re-notif#37]
Hi,

componentClassName has no effect if passed to notifSend action payload, even though the docs say so. From the source it only extracts message and kind from the payload.

Use case is that I want to override the styles for only a specific notification by passing the classname in the payload.

**Comment by kylecesmat** [comment]
@SabeehY I clarified the proper way to use the `componentClassName` prop in #39 - it shouldn't be part of the config, but rather the `Notifs` component as a prop. Sorry about the confusion!
