### ISSUE TITLE
fix bug

### ISSUE THREAD

**Issue by ngthorg** [indexiatech/re-notif#4]
### fix 1
https://github.com/indexiatech/re-notif/blob/master/src/index.js#L3
import NotifsComponent from './components/notifs'
to
import NotifsComponent from './components/Notifs'
### fix 2
https://github.com/indexiatech/re-notif/blob/master/src/components/Notif.js#L59
borderSizing: 'border-box'
to
boxSizing: 'border-box'
### fix 3
https://github.com/indexiatech/re-notif/blob/master/src/components/Notif.js#L91
'background-color': '#71bbff'
to
'backgroundColor': '#71bbff'

thanks all!

**Comment by asaf** [comment]
Thanks, these changes will be pushed in the next release.
