### ISSUE TITLE
Demo code is outdated, does not match live demo

### ISSUE THREAD

**Issue by edslocomb** [indexiatech/re-notif#43]
The demo at http://indexiatech.github.io/re-notif/ has a checkbox control for "Custom Styles"

The code at https://github.com/indexiatech/re-notif/blob/master/demo/index.js does not include that "Custom Styles" control.

The custom styles code _is_ present in https://raw.githubusercontent.com/indexiatech/re-notif/gh-pages/demo.js

**Comment by kylecesmat** [comment]
This should be fixed by #41

**Comment by kylecesmat** [comment]
Oh, actually it won't be. You're right, `gh-pages` needs to be updated!

**Comment by edslocomb** [comment]
outdated, closing
