### ISSUE TITLE
redux-notifications fails to compile with browserify

### ISSUE THREAD

**Issue by patsplat** [indexiatech/re-notif#44]
Browserify fails when requiring redux-notifications.  Provided test project: [redux-notifications-browserify.zip](https://github.com/indexiatech/re-notif/files/507368/redux-notifications-browserify.zip)

```bash
redux-notifications-browserify $ npm install
redux-notifications-browserify $ npm test

> redux-notifications-browserify@1.0.0 test /Users/patrick/Google Drive/redux-notifications-browserify
> node_modules/browserify/bin/cmd.js index.js  -o output.js -t [ babelify --presets [ es2015 react ] ]

redux-notifications-browserify/node_modules/redux-notifications/css/styles.css:1
.notif-transition-enter {
^
ParseError: Unexpected token
npm ERR! Test failed.  See above for more details.
redux-notifications-browserify $
```

**Comment by michelre** [comment]
Yes, I was confronted to the same issue!!

Any solution?

**Comment by patsplat** [comment]
my workaround was to fork Notif and moved the require(css) out of
javascript into my sass build

On Tue, Oct 4, 2016 at 4:26 PM Rémi <notifications@github.com> wrote:

Yes, I was confronted to the same issue!!

Any solution?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/indexiatech/re-notif/issues/44#issuecomment-251502829>,
or mute the thread

**Comment by michelre** [comment]
Thanks, I'll try that! :)

**Comment by kylecesmat** [comment]
This is similar to #36. The CSS is very minimal and is probably better suited to be written inline
