### ISSUE TITLE
Style Loader is Required

### ISSUE THREAD

**Issue by prescottprue** [indexiatech/re-notif#49]
Style loader is required to use this within an application since you import `styles.css` in `index.js`. This works fine in the demo because the demo is using style loader, but will break in any application that isn't using that loader.

It would be nice to have this be a standalone module that doesn't require loaders.

**Comment by kylecesmat** [comment]
Hi @prescottprue - thanks for the report. What version of `redux-notifications` are you using? The latest@3.x exports the styles separately per https://github.com/indexiatech/re-notif/pull/47 and shoudn't require style-loader unless you import the css file.
