### ISSUE TITLE
CSSTransitionGroup: change react-addons-css-transition-group to react-transition-group 

### ISSUE THREAD

**Issue by raulpuente** [indexiatech/re-notif#60]
Hello, i'm using your component and the last version of reactjs, and i got this warning:

warning redux-notifications > react-addons-css-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use CSSTransitionGroup from 'react-transition-group' instead.

Thank you.

**Comment by kylecesmat** [comment]
Thanks for reporting! Yeah, this should be a straight-forward PR if you'd like to contribute. Otherwise, I'll see if I can find time to this soon.

**Comment by raulpuente** [comment]
I've seen that you already have then changes on master branch (changing to CSSTransitionGroup), may be only adding a new tag will be ok?

**Comment by kylecesmat** [comment]
@raulpuente yeah, this was released in `3.2.0`

**Comment by raulpuente** [comment]
Thank you @kylecesmat
