### ISSUE TITLE
Module not found: Can't resolve 'react-transition-group/CSSTransitionGroup'

### ISSUE THREAD

**Issue by rpellerin** [indexiatech/re-notif#62]
I think there is a regression at commit f544bf.
Some `devDeps` should be declared as `dependencies`.

Namely:
- react-transition-group
- object-assign
- prop-types
- react-redux

We should also have `peerDependencies`:
- react
- react-dom

**Comment by revmischa** [comment]
Why is this closed? I still get: Uncaught Error: Cannot find module "react-transition-group/CSSTransitionGroup

Because I use a recent version of https://github.com/reactjs/react-transition-group/blob/master/Migration.md
