### ISSUE TITLE
Support for React 15.x?

### ISSUE THREAD

**Issue by hirako2000** [indexiatech/re-notif#9]
Any plan to support for newer versions of React?

**Comment by jpollard-cs** [comment]
created a [PR for this](https://github.com/indexiatech/re-notif/pull/10) - there don't seem to be any issues running re-notif under react 15, but this is getting in the way of my shrinkwrapping :smiley:

**Comment by kylecesmat** [comment]
I'm working on a fork that removes ReactCSSTransitionGroups, as that's no longer bundled with 15

https://github.com/kylecesmat/re-notif

**Comment by jpollard-cs** [comment]
@kylecesmat awesome! Anything I can do to help expedite completion on that? Are you going to create a branch or publish as a separate npm package (unfortunately license is not standard, but seems like it can be published under a different name)? I'm not sure this if project is being actively maintained..

**Comment by kylecesmat** [comment]
@jpollard-cs I'm going to propose a PR, right now trying to work within the existing API for applying styles, should have that merged on my branch shortly and will propose a PR

**Comment by kylecesmat** [comment]
Proposed PR #11 would resolve this

**Comment by hirako2000** [comment]
Considering PR are stacking up.. We better publish a new lib: _react-notif_ ?

**Comment by jpollard-cs** [comment]
I'll try to see if I can find a way to get in touch with @asaf otherwise yes I'm for this

**Comment by jpollard-cs** [comment]
well I tweeted @ him lol - let's give it the day then start talking about alternatives

**Comment by kylecesmat** [comment]
I'd love to help maintain this package

**Comment by jpollard-cs** [comment]
yep I'd be happy to do so, as well - I did a diff on the standard BSD license and it appears this is pretty much the standard BSD license with some additional protection for contributors (which we will be) so I'm good with that - either way it appears it's still pretty much your standard non-copyleft free software license - I'd be happy to maintain an upstream fork and add you guys as contributors (unless someone else wants to own it)

**Comment by jpollard-cs** [comment]
He returns! Thanks for merging my PR @asaf :smile:

**Comment by asaf** [comment]
Hey guys,
Thanks for participating and your contribution,

Lets make this component more awesome together :-)

@kylecesmat I made you a maintainer because you asked first :-)
(One thing, please don't merge the `lib` folder within this project, I dislike lib code within the source repo)

(@jpollard-cs If there'll be more work I'll add you as well :) )

Asaf.

**Comment by asaf** [comment]
@jpollard-cs Sure!

**Comment by jpollard-cs** [comment]
@asaf please let us know when the npm package is updated

**Comment by kylecesmat** [comment]
@jpollard-cs will do! I'm going to work on polishing my PR and I'll submit for a review on the proposed changes. shouldnt take too long
